config/routes.rb
Rails.application.routes.draw do

  get '/quests', to: "quests#index"
  get '/accept', to: "quests#accept_form"
  get '/already', to: "quests#already"
  post '/create', to: "quests#create"
  post '/accept', to: "quests#accept"
  post '/set_location', to: "quests#set_location"
  post '/commit_location', to: "quests#commit_location"

  get '/active_quests', to: "quests#active_quests"
  get '/available_quests', to: "quests#available_quests"
  get '/completed_quests', to: "quests#completed_quests"
  get '/created_quests', to: "quests#created_quests"
  get '/sort_quests', to: "quests#sort_quests"
  get '/create_quests', to: "quests#create_quests"

  get '/quests/all', to: "quests#all"
  get '/user_accepted_quests_loc', to: "quests#user_accepted_quests_loc"
  get '/user_created_quests_loc', to: "quests#user_created_quests_loc"
  get '/user_completed_quests_loc', to: "quests#user_completed_quests_loc"
  get '/show_checkpoints/:quest_id', to: "quests#show_checkpoints"
  get  '/available_quests_loc', to: 'quests#available_quests_loc'

  get '/user_all_checkins_loc', to: "users#user_all_checkins_loc"
  get '/users/checkins', to: "users#checkin_points"
  get '/users/notifications', to: "users#notifications"
  get '/users/expbar', to: "users#expbar"

  get '/foursquare', to: "foursquare#index", as: 'foursquare'
  get '/redirect', to: "foursquare#redirect"
  post '/pull', to: "foursquare#pull", as: 'pull'

  get '/logout', to: "users#logout", as: 'logout'
  get '/users/profile', to: "users#profile"
  get '/admin-checkin', to: "users#admin_checkin"
  get '/test_login', to: "users#test_login"

  get '/xp', to: "users#xp"
  get '/board', to: "users#boards"

  get '/map', to: "maps#show"

  post '/rewards/create', to: "rewards#create"
  get '/rewards/show', to: "rewards#show"

  root "users#index"

end

app/models/quest.rb
class Quest < ActiveRecord::Base
  belongs_to :creator, class_name: 'User' #alias the quest/user
  has_many :checkpoints
  has_many :rewards
  has_many :user_quests
  has_many :locations, through: :checkpoints
  has_many :users, through: :user_quests
  has_many :user_checkpoints, through: :checkpoints
  before_validation :set_defaults
  before_save :set_time_status, :set_user_status

  validates_presence_of :creator_id, :title, :end_date, :description

  def set_defaults
  	self.start_date ||= Time.now
    self.end_date ||= 1.year.from_now
    self.xp ||= 100
  end


  def self.user_accepted_quests(user)
    quests=[]
    user.user_quests.each do |user_quest|
      quest = Quest.find(user_quest.quest_id)
      quests << quest if user_quest.completed == false && quest.timestatus != 'expired'
    end
    return quests.uniq
  end

  def self.user_available_quests(user)
    Quest.all.select {|quest| quest.timestatus=='current' && quest.userstatus=='open' && quest.creator_id != user.id && quest.users.where(id: user.id).empty?}
  end

  def self.user_created_quests(user)
    quests = Quest.where(creator_id: user.id)
  end

  def self.user_completed_quests(user)
    quests=[]
    user.user_quests.each do |user_quest|
      if user_quest.completed==true
        quests << Quest.find(user_quest.quest_id)
      end
    end
    return quests
  end

  def set_time_status
    if self.start_date > Time.now
      self.timestatus = "unready"
    elsif self.end_date < Time.now
      self.timestatus = "expired"
    else
      self.timestatus = "current"
    end
  end

  def set_user_status
    if self.user_limit <= self.user_quests.count && self.user_limit != -1
      self.userstatus = "full"
    else
      self.userstatus = "open"
    end
  end

  def location
    self.locations.first
  end


end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController

  include UsersHelper
  include BuildHashHelper


  def index
    # also route for active_quests
    @quests = Quest.user_accepted_quests(current_user)
  end

  def active_quests
    @quests = Quest.user_accepted_quests(current_user)
    render partial: "quests/display_quests"
  end

  def available_quests
    @quests = Quest.user_available_quests(current_user)
    @user_quest = UserQuest.new
    render partial: "quests/available_quests"
  end

  def completed_quests
    @quests = Quest.user_completed_quests(current_user)
    render partial: "quests/display_quests"
  end

  def created_quests
    @quests = Quest.user_created_quests(current_user)
    render partial: "quests/display_quests"
  end

  def sort_quests
    @quests = Quest.user_available_quests(current_user)
    @quests.sort! { |a,b| a.xp <=> b.xp }
    render partial: "quests/display_quests"
  end

  def create_quests
    @user_quest = UserQuest.new
    @quest = Quest.new
    render partial: "create_quests"
  end


# API METHODS

  def all
    @quests = Quest.includes(:locations).all
    render json: build_markers(@quests, "quest")
  end

  def show_checkpoints
    @checkpoints = Quest.find(params[:quest_id]).checkpoints
    render json: build_markers(@checkpoints, "checkpoint")
  end

  def user_accepted_quests_loc
    @quests = @user.user_quests.select{|user_quest| !user_quest.completed }
    @quests = @quests.map{|user_quest| user_quest.quest}
    render json: build_markers(@quests, "quest")
  end

  def user_created_quests_loc
    @quests = @user.created_quests
    render json: build_markers(@quests, "quest")
  end

  def user_completed_quests_loc
    @quests = @user.user_quests.where(completed: true)
    @quests = @quests.map{|quest| quest.quest }
    render json: build_markers(@quests, "completed quest")
  end

  def available_quests_loc
    @quests = Quest.all
    @quests = @quests.select {|quest| quest.creator_id != @user.id}
    @quests = @quests.select {|quest| quest.timestatus == 'current'}
    @quests = @quests.select {|quest| quest.userstatus == 'open'}
    @quests = @quests.select {|quest| !quest.users.include?(@user) }
    render json: build_markers(@quests, "quest")
  end

  def expbar

  end

  def accept_form
    @user_quest = UserQuest.new
    @quest = Quest.find(params[:quest_id])
    render partial: "quests/accept_form", layout: false
  end

  def accept
    @user_quest = UserQuest.new(user_quest_params)
    quest_id = params[:user_quest][:quest_id]
    user_id = session[:user_id]
    if @user_quest.save
      quest = Quest.find(quest_id)
      quest.checkpoints.each do |checkpoint|
        UserCheckpoint.create(user_id: user_id, checkpoint_id: checkpoint.id)
      end
      flash[:notice] = "Quest successfully accepted"
      render partial: "quests/accepted", layout: false
    else
      flash[:notice] = "Please try again"
      render partial: "quests/rejected", layout: false
    end

  end

  def create
    @checkpoint = Checkpoint.new
    @quest = Quest.new(quest_params)
    if @quest.save
      render partial: 'quests/quest_loc'
    else
      flash[:notice] = "Please try again"
      render partial: 'quests/rejected'
    end

  end

  def set_location
    params[:location] = params[:checkpoint][:locations]
    @location = Location.new(location_params)
    @location.save

    params[:checkpoint][:location_id] = @location.id

    @checkpoint = Checkpoint.new(checkpoint_params)
    if @checkpoint.save
      @venues = search_venues
      if @venues.empty?
        render plain: "Failed to save, try again"
      else
        render json: @venues
      end
    else
      render plain: "Failed to save, try again"
    end
  end

  def search_venues
    query = @location.name
    ll = [@location.latitude, @location.longitude].join(',')
    api = Fsqr.new(session[:token])
    @venues = api.search(query, ll, @location.id)
  end

  def commit_location
    created_location = Location.find(params[:venue][:location_id])

    if params[:venue][:foursquare_id] == nil
      created_location.destroy
      render plain: "Failed to add - try again"
    end

    entry = Location.find_by(foursquare_id: params[:venue][:foursquare_id])

    if entry
      created_location.checkpoints.update_all(location_id: entry.id)
      created_location.destroy
    else
      created_location.update(venue_params)
    end

    render plain: "Successfully added #{params[:venue][:name]}"
  end

  def already
    @quest = Quest.find(params[:quest_id])
    render partial: "quests/already"
  end

  private

  def checkpoint_params
    params.require(:checkpoint).permit(:instructions, :quest_id, :location_id)
  end

  def user_quest_params
    params[:user_quest][:user_id] = current_user.id #hard code to 1 for local
    params.require(:user_quest).permit(:user_id, :quest_id, :completed)
  end

  def quest_params
    params[:quest][:creator_id] = current_user.id #hard code to 1 for local
    params.require(:quest).permit(:creator_id, :title, :description, :user_limit, :category, :start_date, :xp, :end_date)
  end

  def location_params
    params.require(:location).permit(:name, :street, :city, :state, :zip)
  end

  def venue_params
    params.require(:venue).permit(:name, :venue_type, :second_type, :latitude, :longitude, :foursquare_id, :street, :city, :state, :zip, :country)
  end

end

app/helpers/quests_helper.rb
module QuestsHelper

#need another method in here to check step num, this is rudimentary
#also need to a quest status to filter out quests that arent valid yet, invalid now, etc..
	def user_checkpoint_check(user, checkin)
		#i want the following line to have .where(location_id: location.id) and only load those, however
		#at this time i am not sure it will work because multiple locations may be created. going to fix that.
		user.checkpoints.each do |checkpoint|
			if checkpoint.location.foursquare_id == checkin.foursquare_id
				checkpoint.user_checkpoints.find_by(user_id: user.id).complete!
				user_quest_check(user, checkpoint)
				Notification.create(user_id: user.id, title: "Check Point Completed!", content: "You've completed a checkpoint for #{checkpoint.quest.title.titleize} Keep up the good work!")
			end
		end
	end

	def user_quest_check(user, checkpoint)
		quest = Quest.find(checkpoint.quest_id)
		if quest.user_checkpoints.where(user_id: user.id).all?{|record| record.completed == true}
			quest.user_quests.find_by(user_id: user.id).complete!
			Notification.create(user_id: user.id, title: "QUEST COMPLETE!", content: "You've Completed #{quest.title.titleize} As a reward you get #{quest.xp} XP.")
		end
	end

	def quest_info
		[@quest.title, @quest.xp, @quest.userstatus, @quest.timestatus, @quest.end_date, @quest.category, @quest.description]
	end


end

app/views/quests/_accept_form.haml
.accept_form
  %h2
    = @quest.title
  Category:
  = @quest.category
  %br
  Description:
  = @quest.description
  %br
  Starting:
  = @quest.start_date
  %br
  Ending:
  = @quest.end_date
  %br
  Xp Awarded:
  = @quest.xp
  %br
  %br
  = form_for @user_quest, url: accept_path do |f|
    = f.hidden_field :quest_id, :value => @quest.id
    = f.submit "Accept"

app/views/quests/_accepted.haml
.accepted
  Thank You for accepting this Quest!

app/views/quests/_already.haml
.accept_form
  %h2
    = @quest.title
  Category:
  = @quest.category
  %br
  Description:
  = @quest.description
  %br
  Starting:
  = @quest.start_date
  %br
  Ending:
  = @quest.end_date
  %br
  Xp Awarded:
  = @quest.xp
  %br
  You have already accepted this Quest!

app/views/quests/_available_quests.haml
#black_div
  .list
    -if @quests.length>=1
      %h2 Here are your available quests!
      - @quests.each do |quest|
        .sublist
          %li
            = quest.title
            .indent
              %p
                %b Category:
                =quest.category
              %p
                %b Description:
                =quest.description
              %p
                %b Acceptance status:
                =quest.userstatus
              %p
                %b Time Status:
                =quest.timestatus
              %p
                %b Experience:
                =quest.xp
              %p
                %b First checkpoint:
                =quest.checkpoints.first.location.street

          = form_for @user_quest, url: accept_path do |f|
            = f.hidden_field :quest_id, :value => quest.id
            = f.submit "Accept"
    -else
      %h2 You Have No Available Quests

app/views/quests/_create_quests.haml
#create_quest
  %h2 Create a quest
  %br
  = form_for @quest, url: create_path do |g|
    = g.text_field :title, :placeholder => "Title"
    %br
    %br
    = g.text_area :description, size: "60x12", :placeholder => "Description"
    %br
    %br
    = g.number_field :user_limit, :placeholder => "Acceptance limit"
    = g.text_field :category, :placeholder => "Category"
    = g.datetime_field :start_date, :placeholder => "Start Date"
    = g.datetime_field :end_date, :placeholder => "End Date"
    = g.number_field :xp, :placeholder => "Xp Awarded"
    %br
    %br
    = g.submit "Add your checkpoints!"

app/views/quests/_display_quests.haml
#black_div
  .list
    %h2 Here are your quests!
    %br
    %ol
    - @quests.each do |quest|
      .sublist
        %li
          = quest.title
          .indent
            %p
              %b Category:
              =quest.category
            %p
              %b Description:
              =quest.description
            %p
              %b Acceptance status:
              =quest.userstatus
            %p
              %b Time Status:
              =quest.timestatus
            %p
              %b Experience:
              =quest.xp
            %p
              %b First checkpoint:
              =quest.checkpoints.first.location.street

app/views/quests/_quest_loc.haml
#create_quest
  .checkpoints_create
    = form_for @checkpoint, url: set_location_path, :html => {:id => "check_create"} do |i|
      = i.hidden_field :quest_id, :value => (@quest.id)
      %br
      = i.fields_for :locations do |h|
        = h.text_field :name, :placeholder => "Name (Dev Bootcamp)"
        %br
        = h.text_field :street, :placeholder => "Street (ex. 48 Wall St)"
        %br
        = h.text_field :city, :placeholder => "City (ex. New York)"
        %br
        = h.text_field :state, :placeholder => "State (ex. NY)"
        %br
        = h.text_field :zip, :placeholder => "Zip (ex. 10005)"
      %br
      %br
      = i.text_area :instructions, :placeholder => "Instructions", size: "60x12"
      %br
      = i.submit "Submit!"

app/views/quests/_rejected.haml
.rejected
  Please Try again or accept other Quests.

app/views/quests/_sidebar.haml
#active_but.button Your Active Quests
#available_but.button All Available Quests
#comp_but.button Your Completed Quests
#created_but.button Your Created Quests
#sort_but.button Sort Quests By XP
#create_quest_but.button Create a Quest



/ You should only be able to edit a quest until it's start date begins, not after.
/ Available quests should be active quests, that you haven't accepted, ordered by distance from your last checkin.

app/views/quests/index.haml
#content
  = render 'display_quests'

#options.sidebar
  = render 'sidebar'

app/views/quests/main.haml
.quest_title
  %h1 Quest Page!
  =flash[:notice]

.list
  #enable_quests
    Show Quest Map
  %h2 Here are your quests!
  - @quests.each do |quest|
    = quest.title
    = form_for @user_quest, url: accept_path do |f|
      = f.hidden_field :quest_id, :value => quest.id
      = f.submit "Accept"
    %br
    %br


.create
  %h2 Create a quest
  = form_for @quest, url: create_path do |g|
    = g.text_field :title, :placeholder => "Title"
    = g.text_area :description, size: "60x12", :placeholder => "Description"
    = g.number_field :user_limit, :placeholder => "Acceptance limit"
    = g.text_field :category, :placeholder => "Category"
    = g.datetime_field :end_date, :placeholder => "End Date"
    = g.submit "Add your checkpoints!"
  %br
  %br

#enable_quests
  = "View Quests"
#map