config/routes.rb
Rails.application.routes.draw do

  get '/quests', to: "quests#index"
  get '/accept', to: "quests#accept_form"
  get '/already', to: "quests#already"
  post '/create', to: "quests#create"
  post '/accept', to: "quests#accept"
  post '/set_location', to: "quests#set_location"
  post '/commit_location', to: "quests#commit_location"

  get '/active_quests', to: "quests#active_quests"
  get '/available_quests', to: "quests#available_quests"
  get '/completed_quests', to: "quests#completed_quests"
  get '/created_quests', to: "quests#created_quests"
  get '/sort_quests', to: "quests#sort_quests"
  get '/create_quests', to: "quests#create_quests"

  get '/quests/all', to: "quests#all"
  get '/user_accepted_quests_loc', to: "quests#user_accepted_quests_loc"
  get '/user_created_quests_loc', to: "quests#user_created_quests_loc"
  get '/user_completed_quests_loc', to: "quests#user_completed_quests_loc"
  get '/show_checkpoints/:quest_id', to: "quests#show_checkpoints"
  get  '/available_quests_loc', to: 'quests#available_quests_loc'

  get '/user_all_checkins_loc', to: "users#user_all_checkins_loc"
  get '/users/checkins', to: "users#checkin_points"
  get '/users/notifications', to: "users#notifications"
  get '/users/expbar', to: "users#expbar"

  get '/foursquare', to: "foursquare#index", as: 'foursquare'
  get '/redirect', to: "foursquare#redirect"
  post '/pull', to: "foursquare#pull", as: 'pull'

  get '/logout', to: "users#logout", as: 'logout'
  get '/users/profile', to: "users#profile"
  get '/admin-checkin', to: "users#admin_checkin"
  get '/test_login', to: "users#test_login"

  get '/xp', to: "users#xp"
  get '/board', to: "users#boards"

  get '/map', to: "maps#show"

  post '/rewards/create', to: "rewards#create"
  get '/rewards/show', to: "rewards#show"

  root "users#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
         # :recoverable, :rememberable, :trackable
  include UsersHelper

  has_many :created_quests, class_name: 'Quest', foreign_key: 'creator_id' #alias
  has_many :user_quests
  has_many :quests, through: :user_quests
  has_many :user_rewards
  has_many :rewards, through: :user_rewards
  has_many :user_checkpoints
  has_many :checkpoints, through: :user_checkpoints
  has_many :check_ins
  has_many :locations, through: :check_ins
  has_many :notifications

  before_create :set_defaults

  def completed_quests
    self.user_quests.select{|quest| quest.completed == true}
  end

  def self.sort_users
     @users = User.order(:total_xp).reverse.take(10)
  end

  def set_defaults
    self.total_xp ||= 0
    self.photo_url = "http://www.infragistics.com/media/8948/anonymous_200.gif"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  include BuildHashHelper

  #User Info

  def profile
    @users = User.all
    @rewards = @user.rewards
  end

  def xp
    @quests = Quest.user_completed_quests(current_user)
    @checkins = current_user.check_ins
    render partial: "users/xp"
  end

  # def class_user
  # end

  def notifications
    if logged_in?
      notice = @user.notifications.map {|notice| notice.to_js}
      @user.notifications.clear
      render json: notice
    else
      render json: []
    end
  end

  # def stats
  # end

  def boards
    @users = User.all
    render layout: false
  end

  # Session Methods

  def index
    if logged_in?
      render 'maps/show'
    else
      render 'users/home'
    end
  end

  def test_login
    session[:user_id] = 1 # artificial login for testing purposes
    redirect_to root_path
  end

  def logout
    session.clear
    redirect_to root_path
  end

  def user_all_checkins_loc
    current_user
    checkins = build_markers(@user.check_ins, "checkin")
    render json: checkins
  end

  def checkin_points
    checkins = build_markers(CheckIn.all, "checkin")
    render json: checkins
  end

  def expbar
    render json: {exp:(current_user.total_xp % 1000)}
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def user_creator
    user = User.new
    user.foursquare_id = @api.client.user("self")[:id]
    user.photo_url = @api.client.user("self")[:photo][:prefix] + @api.client.user("self")[:photo][:suffix]
    user.firstname = @api.client.user("self")[:firstName]
    user.lastname = @api.client.user("self")[:lastName]
    user.gender =@api.client.user("self")[:gender]
    user.email = @api.client.user("self")[:contact][:email]
    user.save
    user
  end

  def logged_in?
  	session[:user_id] != nil
  end

end

app/views/users/_home.haml
#slide
  #sign_up_link
    =link_to 'Sign Up', foursquare_path
  #sign_in_link
    =link_to 'Sign In', foursquare_path

app/views/users/_sidebar.haml
%div{id: "info_but", class: "button psuedo_link", href: "/users/profile"} User Info
#xp_but.button XP breakdown
#board_but.button LeaderBoard

app/views/users/_xp.haml
#black_div
  .list
    %h2 Here is your XP Breakdown!
    %br
    %h3 Quests:
    %br
    - @quests.each do |quest|
      .sublist
        %h4
          =quest.title
        =quest.description
        %br
        -quest.checkpoints.each do |checkpoint|
          At :
          =checkpoint.location.name
          %br
        =quest.xp
        xp
        %br
    %br
    %br
    %h3 Checkins:
    %br
    - @checkins.each do |checkin|
      .sublist
        %h4
          =checkin.location.name
          %br
          =checkin.location.address
        =checkin.xp
        xp
        %br
        %br

app/views/users/boards.haml
#black_div
  %h2 The Top Players!
  #board
    %table
      %th First Name
      %th Last Name
      %th Total Xp
      %th Quests Completed
      - @users.sort_by {|user| -user.total_xp}.each do |user|
        %tr
          %td
            =user.firstname
          %td
            =user.lastname
          %td
            =user.total_xp
          %td
            =user.user_quests.where(completed: true).count
  %br
  %h2 Most Completed Quests!
  #board
    %table
      %th First Name
      %th Last Name
      %th Total Xp
      %th Quests Completed
      - @users.sort_by {|user| -user.completed_quests.length}.each do |user|
        %tr
          %td
            =user.firstname
          %td
            =user.lastname
          %td
            =user.total_xp
          %td
            =user.completed_quests.length

app/views/users/home.html.erb
<body class='home'>
  <div id='slide'>
    <h6> Firstperson.io</h6>
      <%=link_to foursquare_path do %>
        <div id='enter_link'>
          Enter
        </div>
      <% end %>
  </div>
</body>

app/views/users/profile.haml
#content
  #black_div
    #user_image
      = image_tag @user.photo_url

    #user_info
      %h2
        = "First Name: #{@user.firstname}"
      %br
      %h2
        = "Last Name: #{@user.lastname}"
      %br
      %h2
        = "Email: #{@user.email}"
      %br
      %h2
        = "Gender: #{@user.gender.capitalize}"
      %br
      %h2
        = "Level: #{@user.total_xp/1000 + 1} Hacker"
      %br

    #rewards
      = render 'rewards/show'

#options.sidebar
  = render 'sidebar'